version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./data/media:/app/media
      - ./data/static:/app/static
      - ./backend:/app  # 开发时方便修改代码
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-your-secret-key-here}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,backend}
      # Face++ API配置
      - FACE_PLUS_PLUS_API_KEY=${FACE_PLUS_PLUS_API_KEY}
      - FACE_PLUS_PLUS_API_SECRET=${FACE_PLUS_PLUS_API_SECRET}
      - FACE_PLUS_PLUS_API_URL=${FACE_PLUS_PLUS_API_URL:-https://api-cn.faceplusplus.com/facepp/v3}
      - FACE_PLUS_PLUS_RETURN_ATTRIBUTES=${FACE_PLUS_PLUS_RETURN_ATTRIBUTES:-gender,age,beauty}
      - FACE_PLUS_PLUS_RETURN_LANDMARK=${FACE_PLUS_PLUS_RETURN_LANDMARK:-0}
      - FACE_PLUS_PLUS_COMPARE_THRESHOLD=${FACE_PLUS_PLUS_COMPARE_THRESHOLD:-70.0}
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8000 facesim.wsgi:application"

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./frontend:/app  # 开发时方便修改代码
    environment:
      - VUE_APP_API_URL=/api
      - NODE_ENV=${NODE_ENV:-production}

volumes:
  media_data:
  static_data: