# Generated by Django 5.2 on 2025-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity_compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='detail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='详情页URL'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='photo',
            field=models.CharField(max_length=500, verbose_name='照片URL'),
        ),
    ]
