# Generated by Django 5.2 on 2025-04-25 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity_compare', '0003_celebrity_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'verbose_name': '名人', 'verbose_name_plural': '名人列表'},
        ),
        migrations.AlterModelOptions(
            name='comparisondetail',
            options={'ordering': ['-similarity'], 'verbose_name': '比对详情', 'verbose_name_plural': '比对详情列表'},
        ),
        migrations.AlterModelOptions(
            name='comparisonresult',
            options={'ordering': ['-created_at'], 'verbose_name': '比对结果', 'verbose_name_plural': '比对结果列表'},
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='gender',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='works',
            field=models.TextField(blank=True, null=True, verbose_name='代表作品'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='face_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Face++ Token'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='processing_status',
            field=models.CharField(choices=[('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='processing', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='处理进度'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会话ID'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='detail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='详情链接'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='face_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Face++ Token'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='photo',
            field=models.ImageField(upload_to='celebrities/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
