# Generated by Django 5.2 on 2025-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity_compare', '0004_alter_celebrity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='处理消息'),
        ),
    ]
