# Generated by Django 5.2 on 2025-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity_compare', '0005_comparisonresult_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开分享'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='share_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='分享码'),
        ),
    ]
